/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard/schedule'
import { Route as DashboardClientsRouteImport } from './routes/dashboard/clients'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAvailabilityRouteImport } from './routes/dashboard/availability'
import { Route as DashboardAgentSettingsRouteImport } from './routes/dashboard/agent-settings'
import { Route as ClientSessionsRouteImport } from './routes/client/sessions'
import { Route as ClientPreferencesRouteImport } from './routes/client/preferences'
import { Route as ClientCalendarRouteImport } from './routes/client/calendar'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvailabilityRoute = DashboardAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentSettingsRoute = DashboardAgentSettingsRouteImport.update({
  id: '/agent-settings',
  path: '/agent-settings',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientSessionsRoute = ClientSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPreferencesRoute = ClientPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCalendarRoute = ClientCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ClientRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/preferences': typeof ClientPreferencesRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/dashboard/agent-settings': typeof DashboardAgentSettingsRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/client/': typeof ClientIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/preferences': typeof ClientPreferencesRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/dashboard/agent-settings': typeof DashboardAgentSettingsRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/client': typeof ClientIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/preferences': typeof ClientPreferencesRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/dashboard/agent-settings': typeof DashboardAgentSettingsRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/client/': typeof ClientIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/client/calendar'
    | '/client/preferences'
    | '/client/sessions'
    | '/dashboard/agent-settings'
    | '/dashboard/availability'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/clients'
    | '/dashboard/schedule'
    | '/client/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/client/calendar'
    | '/client/preferences'
    | '/client/sessions'
    | '/dashboard/agent-settings'
    | '/dashboard/availability'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/clients'
    | '/dashboard/schedule'
    | '/client'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/client/calendar'
    | '/client/preferences'
    | '/client/sessions'
    | '/dashboard/agent-settings'
    | '/dashboard/availability'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/clients'
    | '/dashboard/schedule'
    | '/client/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/availability': {
      id: '/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof DashboardAvailabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent-settings': {
      id: '/dashboard/agent-settings'
      path: '/agent-settings'
      fullPath: '/dashboard/agent-settings'
      preLoaderRoute: typeof DashboardAgentSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/client/sessions': {
      id: '/client/sessions'
      path: '/sessions'
      fullPath: '/client/sessions'
      preLoaderRoute: typeof ClientSessionsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/preferences': {
      id: '/client/preferences'
      path: '/preferences'
      fullPath: '/client/preferences'
      preLoaderRoute: typeof ClientPreferencesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/calendar': {
      id: '/client/calendar'
      path: '/calendar'
      fullPath: '/client/calendar'
      preLoaderRoute: typeof ClientCalendarRouteImport
      parentRoute: typeof ClientRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientRouteChildren {
  ClientCalendarRoute: typeof ClientCalendarRoute
  ClientPreferencesRoute: typeof ClientPreferencesRoute
  ClientSessionsRoute: typeof ClientSessionsRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientCalendarRoute: ClientCalendarRoute,
  ClientPreferencesRoute: ClientPreferencesRoute,
  ClientSessionsRoute: ClientSessionsRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentSettingsRoute: typeof DashboardAgentSettingsRoute
  DashboardAvailabilityRoute: typeof DashboardAvailabilityRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentSettingsRoute: DashboardAgentSettingsRoute,
  DashboardAvailabilityRoute: DashboardAvailabilityRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
